export default {
    document: {
        id: "0:0",
        name: "Document",
        type: "DOCUMENT",
        children: [
            {
                id: "0:1",
                name: "Page 1",
                type: "CANVAS",
                children: [
                    {
                        id: "1:6",
                        name: "Rectangle",
                        type: "INSTANCE",
                        blendMode: "PASS_THROUGH",
                        children: [
                            {
                                id: "I1:6;1:2",
                                name: "Rectangle",
                                type: "RECTANGLE",
                                blendMode: "PASS_THROUGH",
                                absoluteBoundingBox: {
                                    x: 24,
                                    y: -208,
                                    width: 201,
                                    height: 109,
                                },
                                constraints: {
                                    vertical: "SCALE",
                                    horizontal: "SCALE",
                                },
                                fills: [
                                    {
                                        blendMode: "NORMAL",
                                        type: "SOLID",
                                        color: {
                                            r: 0.047774821519851685,
                                            g: 0.9563318490982056,
                                            b: 0.02923285961151123,
                                            a: 1,
                                        },
                                    },
                                ],
                                strokes: [
                                    {
                                        blendMode: "NORMAL",
                                        type: "SOLID",
                                        color: {
                                            r: 0,
                                            g: 0,
                                            b: 0,
                                            a: 1,
                                        },
                                    },
                                ],
                                strokeWeight: 1,
                                strokeAlign: "INSIDE",
                                styles: { fill: "1:12" },
                                effects: [],
                            },
                            {
                                id: "I1:6;18:0",
                                name: "Text",
                                type: "TEXT",
                                blendMode: "PASS_THROUGH",
                                absoluteBoundingBox: {
                                    x: 57,
                                    y: -163,
                                    width: 63,
                                    height: 20,
                                },
                                constraints: {
                                    vertical: "SCALE",
                                    horizontal: "SCALE",
                                },
                                fills: [
                                    {
                                        blendMode: "NORMAL",
                                        type: "SOLID",
                                        color: {
                                            r: 0.8515284061431885,
                                            g: 0.11155396699905396,
                                            b: 0.11155396699905396,
                                            a: 1,
                                        },
                                    },
                                ],
                                strokes: [],
                                strokeWeight: 1,
                                strokeAlign: "OUTSIDE",
                                styles: { fill: "1:11" },
                                effects: [],
                                characters: "Text",
                                style: {
                                    fontFamily: "Roboto",
                                    fontPostScriptName: null,
                                    fontWeight: 400,
                                    fontSize: 12,
                                    textAlignHorizontal: "LEFT",
                                    textAlignVertical: "TOP",
                                    letterSpacing: 0,
                                    lineHeightPx: 14.0625,
                                    lineHeightPercent: 100,
                                    lineHeightUnit: "INTRINSIC_%",
                                },
                                layoutVersion: 0,
                                characterStyleOverrides: [],
                                styleOverrideTable: {},
                            },
                        ],
                        absoluteBoundingBox: {
                            x: 24,
                            y: -208,
                            width: 201,
                            height: 109,
                        },
                        constraints: {
                            vertical: "TOP",
                            horizontal: "LEFT",
                        },
                        clipsContent: false,
                        background: [
                            {
                                blendMode: "NORMAL",
                                visible: false,
                                type: "SOLID",
                                color: { r: 1, g: 1, b: 1, a: 1 },
                            },
                        ],
                        backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                        effects: [],
                        componentId: "1:5",
                    },
                    {
                        id: "7:0",
                        name: "Frame 1",
                        type: "FRAME",
                        blendMode: "PASS_THROUGH",
                        children: [
                            {
                                id: "1:5",
                                name: "Rectangle",
                                type: "COMPONENT",
                                blendMode: "PASS_THROUGH",
                                children: [
                                    {
                                        id: "1:2",
                                        name: "Rectangle",
                                        type: "RECTANGLE",
                                        blendMode: "PASS_THROUGH",
                                        absoluteBoundingBox: {
                                            x: -232,
                                            y: -208,
                                            width: 201,
                                            height: 109,
                                        },
                                        constraints: {
                                            vertical: "SCALE",
                                            horizontal: "SCALE",
                                        },
                                        fills: [
                                            {
                                                blendMode: "NORMAL",
                                                type: "SOLID",
                                                color: {
                                                    r: 0.8515284061431885,
                                                    g: 0.11155396699905396,
                                                    b: 0.11155396699905396,
                                                    a: 1,
                                                },
                                            },
                                        ],
                                        strokes: [
                                            {
                                                blendMode: "NORMAL",
                                                type: "SOLID",
                                                color: {
                                                    r: 0,
                                                    g: 0,
                                                    b: 0,
                                                    a: 1,
                                                },
                                            },
                                        ],
                                        strokeWeight: 1,
                                        strokeAlign: "INSIDE",
                                        styles: { fill: "1:11" },
                                        effects: [],
                                    },
                                    {
                                        id: "18:0",
                                        name: "Text",
                                        type: "TEXT",
                                        blendMode: "PASS_THROUGH",
                                        absoluteBoundingBox: {
                                            x: -199,
                                            y: -163,
                                            width: 63,
                                            height: 20,
                                        },
                                        constraints: {
                                            vertical: "SCALE",
                                            horizontal: "SCALE",
                                        },
                                        fills: [
                                            {
                                                blendMode: "NORMAL",
                                                type: "SOLID",
                                                color: {
                                                    r: 0.047774821519851685,
                                                    g: 0.9563318490982056,
                                                    b: 0.02923285961151123,
                                                    a: 1,
                                                },
                                            },
                                        ],
                                        strokes: [],
                                        strokeWeight: 1,
                                        strokeAlign: "OUTSIDE",
                                        styles: { fill: "1:12" },
                                        effects: [],
                                        characters: "Text",
                                        style: {
                                            fontFamily: "Roboto",
                                            fontPostScriptName: null,
                                            fontWeight: 400,
                                            fontSize: 12,
                                            textAlignHorizontal: "LEFT",
                                            textAlignVertical: "TOP",
                                            letterSpacing: 0,
                                            lineHeightPx: 14.0625,
                                            lineHeightPercent: 100,
                                            lineHeightUnit: "INTRINSIC_%",
                                        },
                                        layoutVersion: 0,
                                        characterStyleOverrides: [],
                                        styleOverrideTable: {},
                                    },
                                ],
                                absoluteBoundingBox: {
                                    x: -232,
                                    y: -208,
                                    width: 201,
                                    height: 109,
                                },
                                constraints: {
                                    vertical: "TOP",
                                    horizontal: "LEFT",
                                },
                                clipsContent: false,
                                background: [
                                    {
                                        blendMode: "NORMAL",
                                        visible: false,
                                        type: "SOLID",
                                        color: {
                                            r: 1,
                                            g: 1,
                                            b: 1,
                                            a: 1,
                                        },
                                    },
                                ],
                                backgroundColor: {
                                    r: 0,
                                    g: 0,
                                    b: 0,
                                    a: 0,
                                },
                                effects: [],
                            },
                        ],
                        absoluteBoundingBox: {
                            x: -255,
                            y: -230,
                            width: 252,
                            height: 151,
                        },
                        constraints: {
                            vertical: "TOP",
                            horizontal: "LEFT",
                        },
                        clipsContent: true,
                        background: [
                            {
                                blendMode: "NORMAL",
                                type: "SOLID",
                                color: { r: 1, g: 1, b: 1, a: 1 },
                            },
                        ],
                        backgroundColor: { r: 1, g: 1, b: 1, a: 1 },
                        effects: [],
                    },
                    {
                        id: "46:0",
                        name: "Frame 1.1",
                        visible: false,
                        type: "FRAME",
                        blendMode: "PASS_THROUGH",
                        children: [
                            {
                                id: "46:1",
                                name: "Rectangle",
                                type: "INSTANCE",
                                blendMode: "PASS_THROUGH",
                                children: [
                                    {
                                        id: "I46:1;1:2",
                                        name: "Rectangle",
                                        type: "RECTANGLE",
                                        blendMode: "PASS_THROUGH",
                                        absoluteBoundingBox: {
                                            x: -232,
                                            y: -16,
                                            width: 201,
                                            height: 109,
                                        },
                                        constraints: {
                                            vertical: "SCALE",
                                            horizontal: "SCALE",
                                        },
                                        fills: [
                                            {
                                                blendMode: "NORMAL",
                                                type: "SOLID",
                                                color: {
                                                    r: 0.8515284061431885,
                                                    g: 0.11155396699905396,
                                                    b: 0.11155396699905396,
                                                    a: 1,
                                                },
                                            },
                                        ],
                                        strokes: [
                                            {
                                                blendMode: "NORMAL",
                                                type: "SOLID",
                                                color: {
                                                    r: 0,
                                                    g: 0,
                                                    b: 0,
                                                    a: 1,
                                                },
                                            },
                                        ],
                                        strokeWeight: 1,
                                        strokeAlign: "INSIDE",
                                        styles: { fill: "1:11" },
                                        effects: [],
                                    },
                                    {
                                        id: "I46:1;18:0",
                                        name: "Text",
                                        type: "TEXT",
                                        blendMode: "PASS_THROUGH",
                                        absoluteBoundingBox: {
                                            x: -199,
                                            y: 29,
                                            width: 63,
                                            height: 20,
                                        },
                                        constraints: {
                                            vertical: "SCALE",
                                            horizontal: "SCALE",
                                        },
                                        fills: [
                                            {
                                                blendMode: "NORMAL",
                                                type: "SOLID",
                                                color: {
                                                    r: 0.047774821519851685,
                                                    g: 0.9563318490982056,
                                                    b: 0.02923285961151123,
                                                    a: 1,
                                                },
                                            },
                                        ],
                                        strokes: [],
                                        strokeWeight: 1,
                                        strokeAlign: "OUTSIDE",
                                        styles: { fill: "1:12" },
                                        effects: [],
                                        characters: "Text",
                                        style: {
                                            fontFamily: "Roboto",
                                            fontPostScriptName: null,
                                            fontWeight: 400,
                                            fontSize: 12,
                                            textAlignHorizontal: "LEFT",
                                            textAlignVertical: "TOP",
                                            letterSpacing: 0,
                                            lineHeightPx: 14.0625,
                                            lineHeightPercent: 100,
                                            lineHeightUnit: "INTRINSIC_%",
                                        },
                                        layoutVersion: 0,
                                        characterStyleOverrides: [],
                                        styleOverrideTable: {},
                                    },
                                ],
                                absoluteBoundingBox: {
                                    x: -232,
                                    y: -16,
                                    width: 201,
                                    height: 109,
                                },
                                constraints: {
                                    vertical: "TOP",
                                    horizontal: "LEFT",
                                },
                                clipsContent: false,
                                background: [
                                    {
                                        blendMode: "NORMAL",
                                        visible: false,
                                        type: "SOLID",
                                        color: {
                                            r: 1,
                                            g: 1,
                                            b: 1,
                                            a: 1,
                                        },
                                    },
                                ],
                                backgroundColor: {
                                    r: 0,
                                    g: 0,
                                    b: 0,
                                    a: 0,
                                },
                                effects: [],
                                componentId: "1:5",
                            },
                        ],
                        absoluteBoundingBox: {
                            x: -255,
                            y: -38,
                            width: 252,
                            height: 151,
                        },
                        constraints: {
                            vertical: "TOP",
                            horizontal: "LEFT",
                        },
                        clipsContent: true,
                        background: [
                            {
                                blendMode: "NORMAL",
                                type: "SOLID",
                                color: { r: 1, g: 1, b: 1, a: 1 },
                            },
                        ],
                        backgroundColor: { r: 1, g: 1, b: 1, a: 1 },
                        effects: [],
                    },
                    {
                        id: "45:0",
                        name: "Hello",
                        type: "TEXT",
                        blendMode: "PASS_THROUGH",
                        absoluteBoundingBox: {
                            x: -255,
                            y: -335,
                            width: 126,
                            height: 45,
                        },
                        constraints: {
                            vertical: "TOP",
                            horizontal: "LEFT",
                        },
                        fills: [
                            {
                                blendMode: "NORMAL",
                                type: "SOLID",
                                color: { r: 0, g: 0, b: 0, a: 1 },
                            },
                        ],
                        strokes: [],
                        strokeWeight: 1,
                        strokeAlign: "OUTSIDE",
                        effects: [],
                        characters: "Hello",
                        style: {
                            fontFamily: "Roboto",
                            fontPostScriptName: null,
                            fontWeight: 400,
                            fontSize: 12,
                            textAlignHorizontal: "LEFT",
                            textAlignVertical: "TOP",
                            letterSpacing: 0,
                            lineHeightPx: 14.0625,
                            lineHeightPercent: 100,
                            lineHeightUnit: "INTRINSIC_%",
                        },
                        characterStyleOverrides: [],
                        styleOverrideTable: {},
                        styles: { text: "97:6" },
                    },
                ],
                backgroundColor: {
                    r: 0.8980392217636108,
                    g: 0.8980392217636108,
                    b: 0.8980392217636108,
                    a: 1,
                },
                prototypeStartNodeID: null,
            },
            {
                id: "28:4",
                name: "Page 2",
                type: "CANVAS",
                children: [
                    {
                        id: "28:5",
                        name: "Frame",
                        type: "FRAME",
                        blendMode: "PASS_THROUGH",
                        children: [
                            {
                                id: "56:6",
                                name: "Group",
                                type: "GROUP",
                                blendMode: "PASS_THROUGH",
                                children: [
                                    {
                                        id: "28:6",
                                        name: "Rectangle",
                                        type: "RECTANGLE",
                                        blendMode: "PASS_THROUGH",
                                        absoluteBoundingBox: {
                                            x: -212,
                                            y: -16,
                                            width: 144,
                                            height: 62,
                                        },
                                        constraints: {
                                            vertical: "TOP",
                                            horizontal: "LEFT",
                                        },
                                        fills: [
                                            {
                                                blendMode: "NORMAL",
                                                type: "SOLID",
                                                color: {
                                                    r: 0.7686274647712708,
                                                    g: 0.7686274647712708,
                                                    b: 0.7686274647712708,
                                                    a: 1,
                                                },
                                            },
                                            {
                                                blendMode: "NORMAL",
                                                type: "GRADIENT_LINEAR",
                                                gradientHandlePositions: [
                                                    {
                                                        x: 0.5,
                                                        y: -3.0616171314629196e-17,
                                                    },
                                                    {
                                                        x: 0.5,
                                                        y: 0.9999999999999999,
                                                    },
                                                    { x: 0, y: 0 },
                                                ],
                                                gradientStops: [
                                                    {
                                                        color: {
                                                            r: 1,
                                                            g: 1,
                                                            b: 1,
                                                            a: 1,
                                                        },
                                                        position: 0,
                                                    },
                                                    {
                                                        color: {
                                                            r: 1,
                                                            g: 1,
                                                            b: 1,
                                                            a: 0,
                                                        },
                                                        position: 1,
                                                    },
                                                ],
                                            },
                                        ],
                                        strokes: [],
                                        strokeWeight: 1,
                                        strokeAlign: "INSIDE",
                                        effects: [],
                                    },
                                ],
                                absoluteBoundingBox: {
                                    x: -212,
                                    y: -16,
                                    width: 144,
                                    height: 62,
                                },
                                constraints: {
                                    vertical: "TOP",
                                    horizontal: "LEFT",
                                },
                                clipsContent: false,
                                background: [],
                                backgroundColor: {
                                    r: 0,
                                    g: 0,
                                    b: 0,
                                    a: 0,
                                },
                                effects: [],
                            },
                        ],
                        absoluteBoundingBox: {
                            x: -294,
                            y: -65,
                            width: 305,
                            height: 136,
                        },
                        constraints: {
                            vertical: "TOP",
                            horizontal: "LEFT",
                        },
                        clipsContent: true,
                        background: [
                            {
                                blendMode: "NORMAL",
                                type: "SOLID",
                                color: { r: 1, g: 1, b: 1, a: 1 },
                            },
                        ],
                        backgroundColor: { r: 1, g: 1, b: 1, a: 1 },
                        effects: [],
                    },
                ],
                backgroundColor: {
                    r: 0.8980392217636108,
                    g: 0.8980392217636108,
                    b: 0.8980392217636108,
                    a: 1,
                },
                prototypeStartNodeID: null,
            },
        ],
    },
    components: {
        "1:5": { key: "", name: "Rectangle", description: "" },
    },
    schemaVersion: 0,
    styles: {
        "1:12": {
            key: "ea017aed6616af00f3c4d59e3d945c8c3e47adca",
            name: "Green",
            styleType: "FILL",
            description: "",
        },
        "1:11": {
            key: "e234400b962ffafce654af9b3220ce88857523ec",
            name: "Red",
            styleType: "FILL",
            description: "",
        },
        "97:6": {
            key: "cc806814e1b9b7d20ce0b6bed8adf52099899c01",
            name: "Body",
            styleType: "TEXT",
            description: "",
        },
    },
    name: "figma-graphql test file",
    lastModified: "2019-08-01T15:03:00.778658Z",
    thumbnailUrl:
        "https://s3-alpha-sig.figma.com/thumbnails/d5909069-4574-46d5-ba90-06853c7ba840?Expires=1572220800&Signature=LOMS-lpev0oFVScFz4TGEO~v~ei1F7YFCDQq2au2p5ZwCpctsz~V9Ury0Nel~UVxfbtFIUhtvdHyngyfVmUm6xDT2bdl5KlDEWp0awhet-hw31ImzS8pb-dw6rM72Aue9woz4T5jZF1wpEmG6iUV0WAXwqI8YCxI9dK1MCcnBnO5pIVwwk1o0du-qc~T75YVFE8E1YJtiKlJDoU7ldp0zJWxGZlAl9ffRAZFyvKlYZpPeRKAzfyRgINbzkGls58gA38EeNFvZOFSpKbe9fxIB-LIllSy-qN0SnkZbCQFHdLzdk4VtBd3J6RiOsjOpzANvLZaheTNLc2xf7TGqCvgvQ__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA",
    version: "156513791",
};
